app:
  title: Dummy
  baseUrl: http://x.x.x.x:3000

organization:
  name: Dummy

backend:
  baseUrl: http://x.x.x.x:3000
  listen:
    port: 7007

catalog:
  rules:
    - allow: [Component, Group, User, Resource, Location, Template, API, Domain, System]
  locations: []
