app:
  title: Dummy # see configmap
  baseUrl: http://localhost:3000

organization:
  name: Dummy

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  database:
    client: better-sqlite3
    connection: ':memory:'

catalog:
  rules:
    - allow: [Component, Group, User, Resource, Location, Template, API, Domain, System]
  locations: []