FROM node:20-bookworm-slim


RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates libsqlite3-dev python3 python3-pip python3-venv g++ build-essential curl graphviz fonts-dejavu fontconfig gnupg && \
    yarn config set python /usr/bin/python3 && \
    rm -rf /var/lib/apt/lists/*

# Install Azul Zulu 21
RUN curl -s https://repos.azul.com/azul-repo.key | gpg --dearmor -o /usr/share/keyrings/azul.gpg &&\
    echo "deb [signed-by=/usr/share/keyrings/azul.gpg] https://repos.azul.com/zulu/deb stable main" | tee /etc/apt/sources.list.d/zulu.list &&\
    apt-get update && \
    apt-get install -y --no-install-recommends zulu21-jre && \
    rm -rf /var/lib/apt/lists/*


# Set up a virtual environment for mkdocs-techdocs-core.
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Install MkDocs
# https://backstage.io/docs/features/techdocs/getting-started#disabling-docker-in-docker-situation-optional
RUN pip3 install mkdocs-techdocs-core markdown-inline-mermaid

RUN yarn global add @mermaid-js/mermaid-cli

# Install CookieCutter
# https://backstage.io/docs/features/software-templates/configuration#disabling-docker-in-docker-situation-optional
RUN pip3 install cookiecutter

# Install PlantUml
RUN curl -o plantuml.jar -L https://github.com/plantuml/plantuml/releases/download/v1.2024.7/plantuml-1.2024.7.jar && mv plantuml.jar /opt/plantuml.jar
RUN echo '#!/bin/sh\n\njava -jar '/opt/plantuml.jar' ${@}' >> /usr/local/bin/plantuml
RUN chmod 755 /usr/local/bin/plantuml

