FROM node:22-bookworm-slim

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates python3 python3-pip python3-venv gcc musl-dev curl graphviz fonts-dejavu fontconfig gnupg git && \
    yarn config set python /usr/bin/python3 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install Azul Zulu 21
RUN curl -s https://repos.azul.com/azul-repo.key | gpg --dearmor -o /usr/share/keyrings/azul.gpg &&\
    echo "deb [signed-by=/usr/share/keyrings/azul.gpg] https://repos.azul.com/zulu/deb stable main" | tee /etc/apt/sources.list.d/zulu.list &&\
    apt-get update && \
    apt-get install -y --no-install-recommends zulu21-jre-headless && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set up a virtual environment for mkdocs-techdocs-core.
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Install MkDocs + CookieCutter
# https://backstage.io/docs/features/techdocs/getting-started#disabling-docker-in-docker-situation-optional
# https://backstage.io/docs/features/software-templates/configuration#disabling-docker-in-docker-situation-optional
RUN pip3 install mkdocs-techdocs-core mkdocs-git-revision-date-localized-plugin cookiecutter mkdocs-section-index

# Install PlantUml
ENV PLANTUML_VERSION=1.2025.2
RUN curl -v -o plantuml.jar -L https://github.com/plantuml/plantuml/releases/download/v${PLANTUML_VERSION}/plantuml-${PLANTUML_VERSION}.jar && mv plantuml.jar /opt/plantuml.jar
RUN echo '#!/bin/sh\n\njava -jar '/opt/plantuml.jar' ${@}' >> /usr/local/bin/plantuml
RUN chmod 755 /usr/local/bin/plantuml

# Install Node.js (already included in the base image) and @techdocs/cli
RUN npm install -g @techdocs/cli

WORKDIR /docs

ENTRYPOINT ["bash"]