#
name: Create and publish Docker image

on:
  workflow_dispatch:
    inputs:
      image-suffix:
        type: choice
        description: Select the image
        options:
          - raw
          - build
          - buil-sqlite3

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      #
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ github.repository_owner }}/backstage-${{ github.event.inputs.image-suffix }}
          tags: |
            type=raw,value={{date 'YYYYMMDD-HHmmss'}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Build and push
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: ./Dockerfile-${{ github.event.inputs.image-suffix }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/backstage-${{ github.event.inputs.image-suffix }}:latest
            ghcr.io/${{ steps.meta.outputs.tags }}
          labels: |
            org.opencontainers.image.description=Backstage Docker image.
